// Generated by CoffeeScript 1.9.2
(function() {
  define(["../js/avalon", "text!../html/pager.html", "css!../css/pager.css"], function(avalon, template) {
    var widget;
    widget = avalon.ui["pager"] = function(el, data, vmodels) {
      return vmodels;
    };
    widget.version = 0.1;
    widget.defaults = {};
    return avalon;
  });

}).call(this);

//# sourceMappingURL=pager.js.map
